version: '3'

services:
    mysql:
        image: mysql:8.0.20
        ports: 
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: trig
            MYSQL_USER: app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
    elasticsearch:
        image: elasticsearch:7.7.1
        ports:
            - "9200:9200"
        volumes:
            - es-data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
    tika: 
        image: apache/tika:1.24.1-full
        ports: 
            - "9998:9998"
    redis:
        image: redis:6.0.5-alpine
        ports: 
            - "6379:6379"
    web:
        build: 
            context: .docker/web
            dockerfile: Dockerfile
        ports:
            - "8090:80"
        volumes:
            - nfsmount:/var/www/html
    php: 
        build: 
            context: .docker/php
            dockerfile: Dockerfile
        entrypoint: .docker/php/entrypoint.sh
        ports:
            - "9000:9000"   
        volumes:
            - nfsmount:/var/www/html

volumes:
    nfsmount: 
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"
    db-data:
    es-data:
        